### PR TITLE
Feature/sync with nco

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**

### CODE REVIEW

**Comment by DingchenHou-NOAA** [comment]
We may want to wait for a while until v12.1.2 is implemented for prod.

**Comment by XianwuXue-NOAA** [comment]
Yes, I submit the PR to let me remember these changes.

**Review by DingchenHou-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
Only one difference: In this repo, we deleted "module load bufr/11.2.0" in sorc/Module_gefs_v12_wcoss_dell_p3, while NCO's version does not. However, it will affect anything.

**Comment by XianwuXue-NOAA** [comment]
Yes. Typo, I meant it will NOT affect anything. Since we have delete the bufr lib synchronizing from NCO's changes on Feb 2,  2021 (Commit: 3e51e61f121e5306a66d5f0f2c980c51387a8cde) and Jan 8, 2021 (8355dee1c761b4c992b325b0134247c827394b00)

**Pull request merged**
