### PR TITLE
3TM requesting GEFSv12_data be added to SBN

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
To request NCEP add WMO headers to a limited subset of GEFSv12 data and for that data to be added to the Satellite Broadcast Network (SBN) to reliably support River Forecast Center (RFC) ensemble river forecast operations using the Hydrologic Ensemble Forecast Service (HEFS).

In this PR, new atmos_awips task is created and I will also add new transfer lists for NCO.

### CODE REVIEW

**Review by BoiVuong-NOAA — APPROVED** [review]
Look good !

**Comment by XianwuXue-NOAA** [comment]
Thanks @BoiVuong-NOAA Please accept my invitation and approve the PR if you think it is good. I will do some tests, when it is done, I will merge the PR.

**Review by BoiVuong-NOAA — APPROVED** [review]
Looks good !

**Review by BoiVuong-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
thanks @BoiVuong-NOAA

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
Thanks. @WalterKolczynski-NOAA

**Pull request merged**
