### PR TITLE
Merge the feature/gefs.v12.3.2 branch into ops branch for GEFS v12.3.3

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
This PR is to merge the feature/gefs.v12.3.2 into ops for the GEFS v12.3.2. This update include the changes below:

  1. firewx dcom path changes
  2. restart capability for ensstat and atmos gempak jobs to solve the BugZilla issue [#1013](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1013) and [#1325](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1325)
  3. ensstat and awips job changes for missing member to fix BugZilla Issue: [#1336](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1336)
  4. Cleanup job changes to exclude gec00.t06z.[sfc|atm]f012.nemsio to solve BugZilla issue: [#1343](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1343)

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
This PR include the previous 4 PRs and three additional commits:

1) [Update rocoto from 1.3.4 to 1.3.5 on WCOSS2](https://github.com/NOAA-EMC/GEFS/pull/84/commits/9645cf0ece8718aab168abe4a2cc2096454046fd)
2) [Update the HOMEDIR using GFS new tag: v12.3.2](https://github.com/NOAA-EMC/GEFS/pull/84/commits/d62eecd66a7daac985731fee120c6f06bab57b6a)
3) [Update the g-w tag for v12.3.2](https://github.com/NOAA-EMC/GEFS/pull/84/commits/f0094578563070465fd2d4ec1244b713091a4024)

I am working on do the last test, @WalterKolczynski-NOAA please review this PR when you have time.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending testing.

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA I have completed the test and confirmed the changes of 2,3 & 4 are expected. I also compared the chem/sfcsig with production and they are identical. @lipan-NOAA Could you please check the chem and see whether it is correct or not? I plan to deliver the code to NCO next Wednesday.

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA will do it today

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA I run it on WCOSS2 and checked CHEM outputs. It is fine for me.

**Comment by XianwuXue-NOAA** [comment]
Sounds great. Thanks @lipan-NOAA

**Pull request merged**
