### PR TITLE
Synchronize NCO's changes and improve scripts

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**

### CODE REVIEW

**Comment by WeiWei-NCO** [comment]
Could you please remove /ecf/defs or replace the files under it with /lfs/h1/nco/idsb/noscrub/Wei.Wei/gefs/defs/wcoss2_prod/gefs_prod??.def

Current ones in para are for para suite instead of prod suite. Sorry for the confusion.

**Comment by XianwuXue-NOAA** [comment]
Thanks Wei. I will replace it.

**Comment by XianwuXue-NOAA** [comment]
@WeiWei-NCO

**Comment by XianwuXue-NOAA** [comment]
@WeiWei-NCO Updated.

**Comment by WeiWei-NCO** [comment]
> @WeiWei-NCO Updated.

Thank you @XianwuXue-NOAA

**Review by DingchenHou-NOAA — APPROVED** [review]

**Comment by DingchenHou-NOAA** [comment]
I approved the PR though not fully understand the settings in COMOUT.
I am sure you have full understanding.

**Comment by XianwuXue-NOAA** [comment]
The COMOUT are from Wei's para. I tested and it works.

**Pull request merged**
