### PR TITLE
Update modules in bin file of atmos_prep

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
1) Update modules in bin file of atmos_prep
2) Improve gefs_config to run using real-time data

 On branch hotfix/develop
	modified:   rocoto/bin/wcoss_dell_p3/atmos_prep.sh
	modified:   rocoto/parm/gefs_config

Refs: #28

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
I have run one cycle on WCOSS_DELL_P3 and everything works well except trackers. I will work on it to make tracker work

**Comment by DingchenHou-NOAA** [comment]
Don't know why module change is needed.

**Comment by XianwuXue-NOAA** [comment]
Because atmos_prep uses chgres_cube, and chgres_cube needs the new modules. In DELL_P35, we have already changed.

**Comment by XianwuXue-NOAA** [comment]
Since we have add global_enspqpf.fd to sorc/. Now, all tasks ran successfully.

**Review by DingchenHou-NOAA — APPROVED** [review]

**Pull request merged**
