### PR TITLE
GBBEPx emission is at least a day later than today

### PR DESCRIPTION
**Pull request by lipan-NOAA**
This PR is recreated for https://github.com/NOAA-EMC/GEFS/issues/65 based on a new branch of feature/gef.v12.3.2

### CODE REVIEW

**Comment by lipan-NOAA** [comment]
@XianwuXue-NOAA please review it

**Review by XianwuXue-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
When you g-w updated, when we can merge this PR to the branch.

**Comment by XianwuXue-NOAA** [comment]
@lipan-NOAA please update the g-w tag in checkout.sh. [gefs_v12.3.2](https://github.com/NOAA-EMC/global-workflow/releases/tag/gefs_v12.3.2)

**Review by XianwuXue-NOAA — APPROVED** [review]
I will change the g-w tag in checkout.sh after the merge

**Pull request merged**
